### ISSUE TITLE
Can't init bot with botToken

### ISSUE THREAD

**Issue by ddk9499** [ErnyTech/JTDLib#1]
I'm using your library, and when creating bot
`val tgBot = BotClient("token")`
getting this exception.
![image](https://user-images.githubusercontent.com/33849788/47437032-30ab6900-d7c1-11e8-9b15-3ad340a1da54.png)

**Comment by ErnyTech** [comment]
JTDLib fails to load Tdlib, please use the new version which includes changes to get more information about this error.
Then send me the logs of what you receive from JTDLib
Thank you

**Comment by ddk9499** [comment]
@ErnyTech it was in mac. If you add support for mac in new version, i will test it, using java. Thank you!

**Comment by ErnyTech** [comment]
ok then, I close the issue
stay informed by looking at the issue https://github.com/ErnyTech/JTDLib/issues/6
