### ISSUE TITLE
JTDLib for Mac

### ISSUE THREAD

**Issue by ivanooi** [ErnyTech/JTDLib#6]
Hi, 

any plan for JTDLib for Mac?

Thanks

**Comment by ErnyTech** [comment]
Yes

Il giorno 7 nov 2018, 09:20, alle ore 09:20, ivanooi <notifications@github.com> ha scritto:

**Comment by ErnyTech** [comment]
I'm working of a new build system for speed up builds of native parts and support more OS (MacOS, Android), this build system need also for fix https://github.com/ErnyTech/JTDLib/issues/3

**Comment by aivel** [comment]
Hi!

Any news on MacOS builds so far?

**Comment by ErnyTech** [comment]
**The development of JTDLib has been discontinued, this issue will not be fixed.**
